name: Build Knowledge Index

on:
  push:
    paths:
      - "knowledge/**"
      - "journal/**"
      - "scripts/build_index.py"
  workflow_dispatch: {}
  # schedule:
    # - cron: "17 7 * * 1" # optional weekly refresh (Mon 07:17 UTC)

permissions:
  contents: write

concurrency:
  group: build-knowledge-index
  cancel-in-progress: false

jobs:
  build-index:
    # Prevent infinite loops if the last commit came from this workflow
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build knowledge/INDEX.md
        run: |
          python scripts/build_index.py

      - name: Commit changes (if any)
        run: |
          git config user.name "study-bot"
          git config user.email "actions@users.noreply.github.com"
          if ! git diff --quiet; then
            git add knowledge/INDEX.md
            git commit -m "bot: refresh knowledge index [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
